uint8 CONTROL_MODE_CMD_MOTION_PRESET=0
uint8 CONTROL_MODE_CMD_MOTION_PRESET_CYCLIC_TOGGLE=1
uint8 CONTROL_MODE_CMD_JOINT_POSITION_HOLD=2
uint8 CONTROL_MODE_CMD_MOTION_STOP=3
uint8 CONTROL_MODE_CMD_WALKMODE_ON=4
uint8 CONTROL_MODE_CMD_LOW_LEVEL_JOINT_CONTROL=5
uint8 CONTROL_MODE_CMD_LOW_LEVEL_WALKMODE_ON=6
uint8 CONTROL_MODE_CMD_HIGH_LEVEL_WALKMODE_ON=7
uint8 CONTROL_MODE_CMD_HIGH_LEVEL_JOINT_CONTROL=8
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_1=9
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_2=10
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_3=11
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_4=12
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_5=13
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_6=14
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_7=15
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_8=16
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_9=17
uint8 CONTROL_MODE_CMD_CUSTOM_MODE_10=18
Header header
string request_id
uint8 command_type
string preset_id
bool is_cyclic
---
Header header
string request_id
bool success
string message
int32 error_code
