uint8 MUJOCO_SIM_PAUSE=0
uint8 MUJOCO_SIM_RESUME=1
uint8 MUJOCO_SIM_RELOAD=2
uint8 MUJOCO_SIM_RESET=3
Header header
string request_id
uint8 command_type
---
Header header
string request_id
bool success
string message
int32 error_code
